function savedataSerialise()
{
    trace("Save: Serialising game variables");
    var _map = ds_map_create();
    ds_map_add(_map, "gameVersion", 102);
    ds_map_add(_map, "moneyJar", global.moneyJar);
    ds_map_add(_map, "tutorialOver", global.tutorialOver);
    ds_map_add(_map, "juicerRankProgress", global.juicerRankProgress);
    ds_map_add(_map, "language", locGetLanguage());
    ds_map_add(_map, "languageSetByUser", global.languageSetByUser);
    ds_map_add(_map, "wideGame", global.wideGame);
    ds_map_add(_map, "fullscreen", global.fullscreen);
    ds_map_add(_map, "userWindowWidth", global.userWindowWidth);
    ds_map_add(_map, "userWindowHeight", global.userWindowHeight);
    ds_map_add(_map, "userWindowPositionX", global.userWindowPositionX);
    ds_map_add(_map, "userWindowPositionY", global.userWindowPositionY);
    ds_map_add(_map, "screenshakeEnabled", global.screenshakeEnabled);
    ds_map_add(_map, "musicEnabled", global.musicEnabled);
    ds_map_add(_map, "soundEnabled", global.soundEnabled);
    ds_map_add(_map, "invertSwipe", global.invertSwipe);
    ds_map_add(_map, "slowerTimeScale", global.accessibilityTimeScale);
    ds_map_add(_map, "hapticEnabled", global.hapticEnabled);
    ds_map_add(_map, "force short screen", global.debugForceShorterPortraitScreen);
    ds_map_add(_map, "debug variable tracker", global.debugDrawVariableTracker);
    ds_map_add(_map, "debug audio engine", global.debugDrawAudioEngine);
    ds_map_add(_map, "notif_equipment", global.notif_equipment);
    ds_map_add(_map, "notif_gacha", global.notif_gacha);
    ds_map_add(_map, "puzzleAreaUnlockNotification", global.puzzleAreaUnlockNotification);
    ds_map_add(_map, "arcadeUnlock", global.arcadeUnlock);
    ds_map_add(_map, "puzzleUnlock", global.puzzleModeUnlocked);
    ds_map_add(_map, "endingReached", global.endingReached);
    ds_map_add(_map, "finalMixReached", global.finalMixReached);
    ds_map_add(_map, "arcadeAreaLock_2", global.arcadeAreaLock[UnknownEnum.Value_2]);
    ds_map_add(_map, "arcadeAreaLock_4", global.arcadeAreaLock[UnknownEnum.Value_1]);
    ds_map_add(_map, "arcadeAreaLock_2_highest", global.arcadeAreaLock_highest[UnknownEnum.Value_2]);
    ds_map_add(_map, "arcadeAreaLock_4_highest", global.arcadeAreaLock_highest[UnknownEnum.Value_1]);
    ds_map_add(_map, "endless score 10", global.endlessHighScore[UnknownEnum.Value_0]);
    ds_map_add(_map, "endless score 8", global.endlessHighScore[UnknownEnum.Value_1]);
    ds_map_add(_map, "endless score 6", global.endlessHighScore[UnknownEnum.Value_2]);
    ds_map_add(_map, "endless score 4", global.endlessHighScore[UnknownEnum.Value_3]);
    ds_map_add(_map, "endless score 2", global.endlessHighScore[UnknownEnum.Value_4]);
    ds_map_add(_map, "puzzle data", puzzleDataExport());
    mapWriteListCopy(_map, "areaUnlockedList", global.areaUnlockedList);
    mapWriteListCopy(_map, "upgrade", global.upgrade);
    mapWriteListCopy(_map, "equipment", global.equipmentSlot);
    mapWriteListCopy(_map, "unlocked ability", global.unlockedAbilityList);
    mapWriteListCopy(_map, "leaderboard scores", global.endlessPackedScoreList);
    mapWriteListCopy(_map, "trophy list", global.achievementTrophyGotList);
    mapWriteListCopy(_map, "endless average 10 current", global.endlessAverageList_current[UnknownEnum.Value_0]);
    mapWriteListCopy(_map, "endless average 8 current", global.endlessAverageList_current[UnknownEnum.Value_1]);
    mapWriteListCopy(_map, "endless average 6 current", global.endlessAverageList_current[UnknownEnum.Value_2]);
    mapWriteListCopy(_map, "endless average 4 current", global.endlessAverageList_current[UnknownEnum.Value_3]);
    mapWriteListCopy(_map, "endless average 2 current", global.endlessAverageList_current[UnknownEnum.Value_4]);
    mapWriteListCopy(_map, "endless average 10 best", global.endlessAverageList_best[UnknownEnum.Value_0]);
    mapWriteListCopy(_map, "endless average 8 best", global.endlessAverageList_best[UnknownEnum.Value_1]);
    mapWriteListCopy(_map, "endless average 6 best", global.endlessAverageList_best[UnknownEnum.Value_2]);
    mapWriteListCopy(_map, "endless average 4 best", global.endlessAverageList_best[UnknownEnum.Value_3]);
    mapWriteListCopy(_map, "endless average 2 best", global.endlessAverageList_best[UnknownEnum.Value_4]);
    var _result = json_encode(_map);
    ds_map_destroy(_map);
    return _result;
}
