event_inherited();
deadSprite = sDeadSpriteDefault;
enemyState = "wander";
stateTimer = 0;
sprite_index = choose(sObakeWanderingTest, sObakeWanderingTest, sObakeWanderingTest, sObakeWanderingTestLarge);
sineTime = pi;
unstompable = 0;
damagePlayer = 1;
grounded = 0;
grav = 0;
gravityEnabled = 0;
maxFallSpeed = 16;
xsp = 1;
ysp = 0;
cx = 0;
cy = 0;
hitStop = 0;
xscaleBase = 1;
yscaleBase = 1;
xDirection = 1;
yDirection = 1;
xShrink = 1;
yShrink = 1;
xscale = xscaleBase * xDirection * xShrink;
yscale = yscaleBase * yDirection * yShrink;
instance_create_depth(x, y, 0, oEnAirBounce);
instance_destroy();
