event_inherited();
currentSequence = "hello message";
currentSequence = "init";
nextTextSign = 1;
oPlayer.xDirection = -1;
oPlayer.ysp = -4;
oPlayer.xsp = 0;
drawDiagbox = 0;
boxOverheadPosY = roomYToGui(oTutJuiceAltar.y) - 16 - 16;
diagbox = diagboxCreate();
diagboxSetKnobTarget(diagbox, roomXToGui(oTutJuiceAltar.x) + 10, roomYToGui(oTutJuiceAltar.y) - 16);
diagboxSetLimits(diagbox, global.windowLeft + 20, (global.windowTop + 20) - 100, global.windowRight - 20, global.windowBottom - 15);
diagboxSetText(diagbox, "a", 1/3);
diagboxSnapToTargetPos(diagbox);
diagboxSetSize(diagbox, 0, 0);
diagboxFloat(diagbox, 0, -8);
diagbox.boxY = boxOverheadPosY;
initializeSequence = 1;
global.jumpTimesMax = 2;
global.jumpTimes = 2;
recordTextPos = 0;
textStoppedTime = 0;
