set = 0;
portalSize = 32;
portalSizeMin = 20;
portalSizeMax = global.viewHeight / 2.5;
mask_surface = -1;
clip_surface = -1;
portalPosx = x;
portalPosy = y;
portalEndPosx = x;
portalEndPosy = 144;
global.portalCam = camera_create_view(0, portalEndPosy - (global.viewHeight / 2), global.viewWidth, global.viewHeight, 0, -1, -1, -1, -1, -1);
view_set_camera(1, global.portalCam);
camera_set_view_size(global.portalCam, global.viewWidth, global.viewHeight);
view_visible[1] = 1;
view_enabled = 1;
maskMultiply = round(display_get_height() / global.viewHeight);
maskWidth = global.viewWidth * maskMultiply;
maskHeight = global.viewHeight * maskMultiply;
camera_set_view_size(global.portalCam, global.viewWidth, global.viewHeight);
portalSurface = surface_create_track(maskWidth, maskHeight);
view_set_surface_id(1, portalSurface);
playerIn = -1;
drawx = global.viewWidth / 2;
drawy = clamp(y, 24 + global.notchOffset + getViewy(global.cam), getViewy(global.cam) + global.viewHeight);
